# Generated by Django 3.2 on 2022-11-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_questions_question_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='correct',
            new_name='option1',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='option_no',
        ),
        migrations.AddField(
            model_name='answers',
            name='option2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='option3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='option4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_no',
            field=models.IntegerField(),
        ),
    ]
