# Generated by Django 3.2 on 2022-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_auto_20221126_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='option4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
