# Generated by Django 3.2 on 2022-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20221126_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
