# Generated by Django 3.2 on 2022-12-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_alter_score_score_val'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ('quiz', 'question_no'), 'verbose_name': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quizes'},
        ),
    ]
